ALTER TABLE CSM_MIGRATE_USER ADD TARGET_IDP_NAME varchar2(100 Byte);
ALTER TABLE CSM_MIGRATE_USER ADD MIGRATION_STATUS varchar2(100 Byte);
/*ALTER TABLE CSM_MIGRATE_USER RENAME COLUMN WUSTLKEY to MIGRATED_LOGIN_NAME;*/

UPDATE CSM_MIGRATE_USER SET MIGRATION_STATUS='MIGRATED' WHERE WUSTLKEY IS NOT NULL;
UPDATE CSM_MIGRATE_USER SET MIGRATION_STATUS='DO_NOT_MIGRATE' WHERE WUSTLKEY IS NULL;

UPDATE CSM_MIGRATE_USER SET TARGET_IDP_NAME='WUSTLKEY_IDP';

ALTER TABLE CSM_MIGRATE_USER MODIFY (MIGRATION_STATUS varchar2(100 Byte) NOT NULL);

