
/*********Inserting Any value in storage type tables********/
insert into CATISSUE_CONTAINER_TYPE (IDENTIFIER,CAPACITY_ID,NAME,ONE_DIMENSION_LABEL,TWO_DIMENSION_LABEL,COMMENTS,ACTIVITY_STATUS) values ( '1',NULL,'Vše',NULL,NULL,NULL,'Disabled');
insert into CATISSUE_CONTAINER_TYPE (IDENTIFIER,CAPACITY_ID,NAME,ONE_DIMENSION_LABEL,TWO_DIMENSION_LABEL,COMMENTS,ACTIVITY_STATUS) values ( '2',NULL,'Any',NULL,NULL,NULL,'Disabled');
insert into CATISSUE_STORAGE_TYPE (IDENTIFIER) values ( '1');
insert into CATISSUE_SPECIMEN_ARRAY_TYPE (IDENTIFIER) values ( '2');
