ALTER TABLE DYEXTN_FORMULA ALTER column expression SET DATA TYPE varchar(4000);

update DYEXTN_CONSTRAINTKEY_PROP set PRIMARY_ATTRIBUTE_ID = null where SRC_CONSTRAINT_KEY_ID in
(
select identifier from DYEXTN_CONSTRAINT_PROPERTIES where CATEGORY_ASSOCIATION_ID in
(select identifier from DYEXTN_CATEGORY_ASSOCIATION)
) and PRIMARY_ATTRIBUTE_ID is not null;

update DYEXTN_CONSTRAINTKEY_PROP set PRIMARY_ATTRIBUTE_ID = null where TGT_CONSTRAINT_KEY_ID in
(
select identifier from DYEXTN_CONSTRAINT_PROPERTIES where CATEGORY_ASSOCIATION_ID in
(select identifier from DYEXTN_CATEGORY_ASSOCIATION)
) and PRIMARY_ATTRIBUTE_ID is not null;

commit;
